name: familycal
description: FamilyCal – geteilter Familienkalender (Phasen 1 & 2 Grundgerüst)
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_messaging: ^14.7.9
  cloud_functions: ^4.7.3
  intl: ^0.19.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  collection: ^1.18.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
